language: node_js
node_js:
  - node # uses most recent stable node version
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "younote-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy:
  - npm run build-client # make the bundle
  - rm -rf node_modules # omit from the tarball, since we skip cleanup
deploy:
  skip_cleanup: true
  provider: heroku
  app: younotebook
  api_key:
    secure:
      WysSCG4gGyqYqOsbHwVoBJGpE9Y3FIX2nfhh708rtDcOSD7O3/qCu+QSZZ1zF9MGdeTcmQ4Nor3BvoAUBL7FRJvIIqIUh+/VX+9vEXpjHWahLkNazCvfKBw6KeLYwlmsE6fJhVRzleiZhx8sXYXVvpR8CjFoJiWgEvxM9A7iCuNuSbecdz10m+W5stRmABm8dQmj0hTQ6cjlSTLW1xElBg92fCw2Q6+LtOdGAPXXuR3ROa942VzZEes2IjHzAQYIFDz5Irpif4dGq2eW59mjjOsTVjMUa+7q5jFL/4qRP6ENcoCc/RWyIvQWBJjgsbLT22HwwW0meRx6XMAIYI19oVUwqM+UafadR90FhSg5ADpMb5qMjng40qerAepisi38oJoAOQFAJPVTmVdpWcPGCipgvxI27QBEOmuof6uHFXLUtuuxTm49m9i9Be2Ig8XuIHdda7TIi64d+eLhBE9mg6XpXVPSqM4vArZmmK3j5M4VDgWZEwKJgzP0b6p76Dt8ZJjC9/KSfTuRA3WKRf3Eja/TFNewgkTdcRwGk7DNISbDKLikOxjiMhk8qUFD0Us1JR/okOQ7ig6nZOugs7/L2cvQ/lk60Ut4KIdE0RkkjhS4bAaWtZeTKz80OuvW+ZpY2bionjDJ2A6YnkZoeTd0JOdqy2dtfFkc/+kSAQvwa08=
